user root;
pid /tmp/nginx.pid;
error_log /dev/stderr warn;

events {}

http {
    access_log /dev/stdout;
    error_log /dev/stderr warn;
    client_body_temp_path /tmp/client_temp;
    proxy_temp_path /tmp/proxy_temp;
    fastcgi_temp_path /tmp/fastcgi_temp;
    uwsgi_temp_path /tmp/uwsgi_temp;
    scgi_temp_path /tmp/scgi_temp;

    upstream docker_socket {
        server unix:/var/run/docker.sock;
    }

    server {
        listen 2375;

        location = /_ping {
            proxy_pass http://docker_socket;
        }

        location = /version {
            proxy_pass http://docker_socket;
        }

        location ~ ^/v[0-9.]+/(_ping|version)$ {
            limit_except GET { deny all; }
            proxy_pass http://docker_socket;
        }

        location ~ ^/v[0-9.]+/containers/(covscript-sandbox|covscript-web)/json$ {
            limit_except GET { deny all; }
            proxy_pass http://docker_socket;
        }

        location ~ ^/v[0-9.]+/containers/(covscript-sandbox|covscript-web)/restart$ {
            limit_except POST { deny all; }
            proxy_pass http://docker_socket;
        }

        location / {
            return 403;
        }
    }
}